import java.util.Scanner;
import java.util.Random;
public class Play
{
  public static void main(String[] args) 
  {
      Scanner sc=new Scanner(System.in);
      System.out.println("----------------------");
      System.out.println("WELCOME TO BINGO GAME");
      System.out.println("----------------------");
      while(true)  /*To have the infinite loop*/
      {
       System.out.println("Choose your option\n1.How to Play\n2.Start Game\n3.Exit");
       int choice=sc.nextInt();
       switch(choice)
       {
           case 1 :  
               System.out.println("Bingo 1-25. In the 5-by-5 grid, with numbers 1-25 in any order, first turn goes to player and selects any number. In horizontal, vertical or diagonal to select five digits can be connected into a line, and the next turn goes to computer and generates a number, the first to reach five connections to win; if completed simultaneously connect more wins.");
               break;
           case 2 :
               BingoGame.InputNum();
               break; 
           case 3 :
               System.out.println("Thank you for visiting!!!\nHave a nice day!");
               System.exit(0);
           default :
               System.out.println("Enter a valid input");
       }
      }
  }
}
class BingoGame
{
  static void InputNum()
  {
    Scanner sc=new Scanner(System.in);  /*Object creation for scanner class*/ 
    Random bingo=new Random();  /*Object creation for random class*/ 
    int player[][]=new int[5][5];
    int temp[]=new int[25];
    int comp[][]=new int[5][5];
    String display[]={"1st","2nd","3rd","4th","5th","6th","7th","8th","9th","10th","11th","12th","13th","14th","15th","16th","17th","18th","19th","20th","21th","22th","23th","24th","25th"};
    System.out.println("Enjoy Playing the Game");
    System.out.println("----------------------");
    System.out.println("Enter 25 numbers each one after the other in the sequence you want in your game : ");
    for(int i=0;i<25;i++)  /*To take input of 25 numbers from user*/
    {
       System.out.println("Enter "+display[i]+" number : ");
       temp[i]=sc.nextInt();
       if(i==0) 
       {
            while(temp[i]<1 || temp[i]>25)
            {
                System.out.println("Enter the number only between 1 and 25 : ");
                temp[i]=sc.nextInt();
            }
       }
       for(int j=0;j<i;j++)  /*To check whether the inputted number reaching the required conditions or not*/
       {
            while(temp[i]<1 || temp[i]>25) /*To get the numbers only between 1 and 25, the user will be prompted to input again*/
            {
                System.out.println("Enter the number only between 1 and 25 : ");
                temp[i]=sc.nextInt();
            }
            if(temp[j]==temp[i])  /*To get only distinct numbers, the user will be prompted to input again if he enters a duplicate number*/
            {
                System.out.println("Please enter the number which is not duplicate : ");
                temp[i]=sc.nextInt();
                j=-1;
            }
        }
      }
      int k=0;
      System.out.println("Your Bingo Board");
      System.out.println("----------------");
      for(int i=0;i<5;i++)  /*Storing the numbers of 1D array into 2D array*/
      {
          for(int j=0;j<5;j++)
          {
              player[i][j]=temp[k++];
          }
      }
      printArray(player);  //Method call
      for(int i=0;i<25;i++)
      {
          temp[i]=1+bingo.nextInt(25); /*To generate random numbers between 1 and 25*/
          for(int j=0;j<i;j++)  /*If the number generated is duplicate, another number will be generated till the number is distinct*/
          {
              if(temp[j]==temp[i])
              {
                  i--;
                  break;
              }
          }
       }
       k=0;
       for(int i=0;i<5;i++) /*Storing the numbers in 1D array into 2D array*/
       {
            for(int j=0;j<5;j++)  /*Storing the numbers of 1D array into 2D array*/
            {
                comp[i][j]=temp[k++];
            }
       }
       chooseNumber(player,comp);  //Method call
       System.out.println("Choose your option\n1.Go to menu\n2.Do you want to look at the computer's bingo board\n3.Exit");
       int option=sc.nextInt();
       int flag=0;
       do
       {
        switch(option)
        {
           case 1 :
                flag=0;
                break;
           case 2 :
                k=0;
                System.out.println("Computers's Board");
                System.out.println("-----------------");
                for(int i=0;i<5;i++)  /*Displaying the array generated by random class before playing the game*/
                {
                   for(int j=0;j<5;j++)
                   {
                       System.out.print(temp[k++]+" ");
                   }
                   System.out.println();
                }
                System.out.println("After replacing the numbers with 0");
                System.out.println("----------------------------------");
                 printArray(comp);  //Method call
                 flag=0;
                 break; 
             case 3 :
                 System.out.println("Thank you for visiting!!!\nHave a nice day!");
                 System.exit(0);  /*To terminate executing*/
             default:
             System.out.println("Enter a valid input : ");
             option=sc.nextInt();
             flag=1;
        }   
       }while(flag==1);     
  }
  static void chooseNumber(int player[][],int comp[][])   //Static Method
  {
      Scanner sc=new Scanner(System.in);
      Random bingo=new Random(); 
      int numbers[]=new int[25];
      for(int i=0;i<25;i=i+2) 
      {
          System.out.println("Choose your number : ");
          numbers[i]=sc.nextInt();
          if(i==0)  /*To check for the first inputted number is between 1 and 25*/
          {
              while(numbers[i]<1 || numbers[i]>25)  
            {
                 System.out.println("Enter the number only between 1 and 25 : ");
                 numbers[i]=sc.nextInt();
            }
          }
          for(int j=0;j<i;j++)
          {
              while(numbers[i]<1 || numbers[i]>25) /*If the choosen number is not between 1 and 25, the user will be prompted to input again*/
              {
                 System.out.println("Enter the number only between 1 and 25 : ");
                 numbers[i]=sc.nextInt();
              }
              if(numbers[i]==numbers[j])  /*If the number entered by the user is already choosen,  the the user will be prompted to input again*/
              {
                  System.out.println("This number is already choosen, please choose another number : ");
                  numbers[i]=sc.nextInt();
                  j=-1;
              }
          }
          for(int k=0;k<5;k++)  /*Replacing the number which is choosen with 0*/
          {
              for(int l=0;l<5;l++)
              {
                  if(player[k][l]==numbers[i])
                  {
                      player[k][l]=0;
                  }
                  if(comp[k][l]==numbers[i])
                  {
                      comp[k][l]=0;
                  }
              }
          }
          System.out.println("Your board after replacing the number you have choosen : ");
          printArray(player);  //Method call
          numbers[i+1]=1+bingo.nextInt(25);  /*Generating the numbers between 1 and 25*/
        for(int j=0;j<=i;j++)  
        {
          if(numbers[j]==numbers[i+1])  /*If the number generated is duplicate, another number will
                                                                   generated till the number is distinct*/
          {
              numbers[i+1]=1+bingo.nextInt(25);
              j=-1;
          }
        }
        System.out.println("Computer has generated "+numbers[i+1]);
        for(int k=0;k<5;k++)   /*Replacing the number which is generate by random class with 0*/
        {
            for(int l=0;l<5;l++)
            {
                if(player[k][l]==numbers[i+1])
                {
                    player[k][l]=0;
                }
                if(comp[k][l]==numbers[i+1])
                {
                    comp[k][l]=0;
                }
            }
        }
        System.out.println("Your board after replacing the number that has choosen by computer : ");
        printArray(player);
        if(check(player)==5 && check(comp)==5)  
        {
          System.out.println("It's a draw");
          break; 
        }
        else if(check(player)==5)
        {
            System.out.println("Congratulations! You won the game");
            break;
        }
        else if(check(comp)==5)
        {
            System.out.println("You lost the game, Better luck next time!");
            break;
        }
      }
  }
  static int check(int arr[][])
  {
     int count=0;
     for(int k=0;k<5;k++)  /*Check for rows*/
     { 
         if(arr[k][0]==0 && arr[k][1]==0 && arr[k][2]==0 && arr[k][3]==0 && arr[k][4]==0)  
         {
             count++;
         }
     }
     for(int k=0;k<5;k++)  /*Check for columns*/
     {
         if(arr[0][k]==0 && arr[1][k]==0 && arr[2][k]==0 && arr[3][k]==0 && arr[4][k]==0)
         {
             count++;
         }
     }
     if(arr[0][0]==0 && arr[1][1]==0 && arr[2][2]==0 && arr[3][3]==0 && arr[4][4]==0)  /*Check for            
                                                                                                                                                        diagonal*/
     {
         count++;
     }
     if(arr[0][4]==0 && arr[1][3]==0 && arr[2][2]==0 && arr[3][1]==0 && arr[4][0]==0)  /*Check for 
                                                                                                                                                        diagonal*/
     {
         count++;
     }
     return count;
  }
  static void printArray(int arr[][])  //Static Method
  {
      for(int k=0;k<5;k++)
          {
              for(int l=0;l<5;l++)
              {
                  System.out.print(arr[k][l]+" ");
              }
              System.out.println();
          }
  }
}
